src/Entity/SectionableInterface.php
<?php

/*
 * This file has been created by developers from BitBag.
 * Feel free to contact us once you face any issues or want to start
 * another great project.
 * You can find more information about us on https://bitbag.shop and write us
 * an email on mikolaj.krol@bitbag.pl.
 */

declare(strict_types=1);

namespace BitBag\SyliusCmsPlugin\Entity;

use Doctrine\Common\Collections\Collection;

interface SectionableInterface
{
    public function initializeSectionsCollection(): void;

    /**
     * @return Collection|SectionInterface[]
     */
    public function getSections(): ?Collection;

    /**
     * @param SectionInterface $section
     *
     * @return bool
     */
    public function hasSection(SectionInterface $section): bool;

    /**
     * @param SectionInterface $section
     */
    public function addSection(SectionInterface $section): void;

    /**
     * @param SectionInterface $section
     */
    public function removeSection(SectionInterface $section): void;
}

src/Resources/views/Shop/Page/Show/_link.html.twig
<a class="bitbag-page-link item" href="{{ path('bitbag_sylius_cms_plugin_shop_page_show', {'slug' : page.slug}) }}">{{ page.name }}</a>

src/Resources/views/Shop/Page/Show/_sections.html.twig
{% if page.sections|length > 0 %}
	<strong> {{ 'bitbag_sylius_cms_plugin.ui.sections'|trans }}: </strong>
	{% for section in page.sections %}
	    <a href="{{ path('bitbag_sylius_cms_plugin_shop_page_index_by_section_code', {'sectionCode' : section.code}) }}" class="ui label">{{ section.name }}</a>
	{% endfor %}
{% endif %}